name: learn_with_ar
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  transparent_image: ^0.1.0
  cupertino_icons: ^1.0.0
  arcore_flutter_plugin: ^0.0.10   # To see enable arcore functionality
  model_viewer: ^0.8.1             # To render the objects only .glb format
  flutter_cube: ^0.0.6
  flutter_login: ^1.0.14
  intl: ^0.16.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  flutter_staggered_grid_view: ^0.3.4
  material_floating_search_bar: ^0.2.6
  cloud_firestore: ^0.16.0
  provider: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/DNA.mtl
    - assets/DNA.obj
    - assets/logo.png
    - assets/pump.glb
    - assets/spinnervlll.gif
